In [2]:
#empty array
arr = []
# with values
arr = [1, "eels"]

# get item by index (can be negative to access end of array)
arr = [1,2,3,4,5,6]
print (arr[0])
print (arr[-1])

length = len(arr)
print ("length of the array is:" + str(length)  )
arr.append(8)
arr.insert(6, 7)
length = len(arr)
print (" new length of the array is:" + str(length)  )

print (arr[-1])

# for calculation 
import numpy as np
a = np.ones((3,2)) # a 2D array with 3 rows, 2 columns filled with ones
b = np.array([1,2,3]) # a 1D array
c = np.linspace(2,3,100) # an array with 100 point between 2 and 3

print (a*1.5) 
print ( a.T+b)

1
6
length of the array is:6
 new length of the array is:8
8
[[1.5 1.5]
 [1.5 1.5]
 [1.5 1.5]]
[[2. 3. 4.]
 [2. 3. 4.]]


First LeetCode solution

In [3]:
def removeDuplicatesFromArray(nums):
    resArray =[]
    k = 0
    dupCount=0
    #for x in array:
        #do something
    #    break
    #for i in range(len(array)):
    #    print (array[i])
        
    for i in range(len(nums)):
        if len(nums) == 1:
            return 1
        
        if i == 0:
            resArray.append(nums[i])
        else:
            if (nums[i-1] == nums[i]):
                dupCount +=1
            
            else:
                resArray.append(nums[i])
                #print (str(dupCount))
                dupCount = 0
    k = len(resArray)    
    for x in range(len(nums)-len(resArray)):
        resArray.append('_')
    nums = resArray
    #print (nums)
    return k, nums


In [4]:
#nums = [0,0,0,1,1,1,2,2,2,2,3,3,4]
nums = [1,1,2]
#nums = [0,0,1,1,1,2,2,3,3,4]

res = removeDuplicatesFromArray(nums)

print (str(res[0])+",", "nums = "+ str(res[1]))

2, nums = [1, 2, '_']
